  MODULE('VOORRAAD029.CLW')
VulPartij_InkoopKGPrijs PROCEDURE                     !het aanroepen van de voorraadclas heb ik uitgeschakeld !!!!
BrowsePallet           PROCEDURE                      !Browse the Pallet file
UpdatePallet           PROCEDURE                      !Form Pallet
ProcessCelLocatieVullen PROCEDURE
ProcessGebruikerLogTerugzetten PROCEDURE              !Uit GebruikerLog File Partij, Verkoop en Planning terughalen
  END
