USE [Voorraad]
GO

/****** Object:  Table [dbo].[Pallet]    Script Date: 02/24/2014 11:42:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pallet](
	[PalletID] [int] IDENTITY(1,1) NOT NULL,
	[Dummy] [varchar(1)] NULL,
 CONSTRAINT [PK_Pallet] PRIMARY KEY CLUSTERED 
(
	[PalletID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Weging] ADD PalletID INT 




